ashish10alex/vscode-dataform-tools

- package.json
- src/extension.ts
- src/utils.ts
Fixes https://github.com/ashish10alex/vscode-dataform-tools/issues/10 by adding a timeout option which has been defaulted to 5 minutes and can be configured in VS Code settings
> fix: compilation timeout on larger projects

- package.json
- src/commands.ts
- src/extension.ts
- src/utils.ts
Fixes https://github.com/ashish10alex/vscode-dataform-tools/issues/10 by adding `--timeout` flag which can optionally be configured in vscode settings similar to the fix for compilation in https://github.com/ashish10alex/vscode-dataform-tools/pull/11
> fix: compilation timeout when running a file / tag 

- README.md
- package.json
- src/commands.ts
- src/extension.ts
- src/multiStageSelector.ts
- src/runFilesTagsWtOptions.ts
- src/utils.ts
Solves: https://github.com/ashish10alex/vscode-dataform-tools/issues/20
1.  Introduce a command `Dataform: Run file(s) / tag(s) with options`  which opens the command pallets gives users option to 
2. Deprecate separate `Run multiple files` command and will be available as an option through (1) 
**Stage 1:** 
1. Run current file 
3. Run a tag
4. Run multiple files 
5. Run multiple tags
**Stage 2:**  Select weather to include dependencies or dependents 
**Stage 3:**  Select weather to do full refresh 
On clicking `Enter` after Stage 3 the command is generated and ran on the terminal 
-------
> feat: Ability to choose more options when running file(s) / tag(s)

- src/hoverProvider.ts
- src/types.ts
I think this is a nice feature to quickly see additional info on a referenced table. 
But please feel free to either just close or redo PR - first time with TS. 
This pull request introduces a new function to provide detailed hover information for tables in the `src/hoverProvider.ts` file and updates the `Table` interface in `src/types.ts` to include BigQuery configuration. The most important changes include the addition of the `getTableInformationFromRef` function and the modification of the `Table` interface.
* [`src/hoverProvider.ts`](diffhunk://#diff-07c4f16ecf031651eef822bcbfc4951045c0e47cb24ef35e1f0467145b1ce8a6R8-R36): Added `getTableInformationFromRef` function to provide detailed hover information, including the table's database, schema, type, partition, and dependencies.
* …
> Additional table information on hover 

- media/css/query.css
- media/js/showCompiledQuery.js
- src/definitionProvider.ts
- src/dependancyTree.ts
- src/extension.ts
- src/hoverProvider.ts
- src/runFiles.ts
- src/types.ts
- src/utils.ts
- src/views/register-preview-compiled-panel.ts
This PR 
**Compilation webview**
**Cleanup** 
Screenshot of how a compilation error will show on webview
> feat: faster and improved compilation webview

- src/definitionProvider.ts
- src/extension.ts
- src/utils.ts
This PR:
Test case where the above implementation works 
```js
config {
type: 'table'
}
/*
create a parameters.js file in the includes directory and add 
getDateMonthsBefore function
function getDateMonthsBefore(date, months) {
date.setMonth(date.getMonth() + months);
let date_string = date.toISOString().split('T')[0];
date_string = `'${date_string}'`;
return date_string
}
*/
js {
const six_months_ago_from_now = parameters.getDateMonthsBefore(new Date(), -6)
const four_months_ago_from_now = parameters.getDateMonthsBefore(new Date(), -6)
const some_month = "january"
const some_number = 11;
let some_coniditon = true;
let another_coniditon = true;
var some_floating_points = 9.4;
}
select 
*
, ${six_months_ago_from_now} as some_time
, ${four_months_ago_from_now} as some_time
, ${some_number} …
```
> feat: simplify go to definition for js variables 

- src/definitionProvider.ts
- src/utils.ts
This PR 
related to https://github.com/ashish10alex/vscode-dataform-tools/pull/51
Tested against following input .Updated with scenarios which would have previously failed
```js
config {
type: 'table'
}
/*
create a parameters.js file in the includes directory and add 
getDateMonthsBefore function
function getDateMonthsBefore(date, months) {
date.setMonth(date.getMonth() + months);
let date_string = date.toISOString().split('T')[0];
date_string = `'${date_string}'`;
return date_string
}
*/
js {
let some_mod = require("includes/parameters.js")
const team = "barcelona"
const six_months_ago_from_now = some_mod.getDateMonthsBefore(new Date(), -6)
const four_months_ago_from_now = some_mod.getDateMonthsBefore(new Date(), -6)
const some_month = "january"
const some_number = 11;
const barcelona = …
```
> feat:  make finding the position of js variable / functions more robust

- snippets/bigquery.code-snippets.json
Just some small changes to the bq snippets. 
Changed the table references from `project.dataset.table` to table_reference. 
This works nicely with the autocompletions on $ like this:
https://github.com/user-attachments/assets/8a4a829e-250e-4af8-bcc4-91067e3f1110
I also dropped the snippets that most likely will never be used inside of dataform to reduce clutter.
> feat: Improved BigQuery snippets

- media/js/showQueryResults.js
- src/bigqueryRunQuery.ts
This PR:
related to https://github.com/ashish10alex/vscode-dataform-tools/pull/62
ensure that single variable `bigQueryJobId` is used to identify bigquery job id
> chore: consistent variable names for bigQuery job id

- media/js/showQueryResults.js
- src/bigqueryRunQuery.ts
- src/views/register-query-results-panel.ts
Here’s a well-formatted version of your GitHub pull request description:
---
This PR introduces a feature that allows users to view a preview query job directly in the BigQuery console.  
- Clicking the link takes the user to the corresponding query job in BigQuery.
- This eliminates the need to manually copy the compiled query for ad-hoc testing in BigQuery.
- I’d appreciate help verifying that the method I use to parse the `bigQueryJobId` into a functional link works for others, as it currently works for me.
_The user needs to have BQ Job List permission in GCP to be able to use the link._
There might be a better way to fetch the job ID, as we currently use two similar variables inside of the window event listener (`jobId` and `bigQueryJobId`). This could potentially lead to confusion.
> feat: add bq link to preview query view

- .vscode/extensions.json
- .vscode/tasks.json
- esbuild.js
- package-lock.json
- package.json
I have used the [following guidelines provided by vscode](https://code.visualstudio.com/api/working-with-extensions/bundling-extension) to bundle extensions using rebuild. It's supposed to improve activation speed as it compiled everything to single `dist/estension.js` file and loading 1 file is faster than loading x files  as per the docs. Not sure how perceptible the performance impact will be for our extension which I assume falls under small/medium. The change in this PR works when you invoke the debugger and use this branches version of the extension. 
I have not personally done this before, so I am not confident what will happen when I will try to publish it and will it work. 
My expectations from this change is - 
* Improvement in activation time of the extension when a new window …
> feat: bundling extension using vscode using esbuild

- README.md
- media/css/query.css
- media/js/showCompiledQuery.js
- src/extension.ts
- src/globals.d.ts
- src/runFiles.ts
- src/utils.ts
- src/views/register-preview-compiled-panel.ts
The change is largely made to make the extension features more visible to a more casual user. 
Minor fixes for issues discovered while implementing this feature
> feat: trigger table run & data preview directly from compiled web ui

- src/utils.ts
While investigating the issue with dry runs failing when `@@query_labels` is set, I couldn’t pinpoint the exact cause. However, I’ve implemented a quick (and perhaps somewhat dirty) solution: dropping the `@@query_labels` statement during dry runs. 
The solution uses a regular expression to identify and remove the `@@query_labels` statement. While the regex might not be entirely foolproof, it has worked in all the scenarios I’ve tested.
Since query labels should not affect dry runs, I don’t foresee any issues with this approach. That said, if you have concerns or an alternative solution, Feel free to change it or let me know :-)
> fix: dry run not working with @@query_label

- README.md
- media/js/showCompiledQuery.js
- src/bigqueryDryRun.ts
- src/globals.d.ts
- src/types.ts
- src/utils.ts
- src/views/register-preview-compiled-panel.ts
Add description column to the table schema shown in the compiled query web view view nav bar. From my testing on Dataform graph with approx 280 nodes this functionality adds **less than 20ms overhead**. Also since computation is performed post the compiled query is displayed, the perceived latency is quite low / imperceptible to human eye.
**Other minor changes**
> feat: show column description in the  table schema 

- src/setDiagnostics.ts
- src/utils.ts
- src/views/register-preview-compiled-panel.ts
feat: propagate pre and post operation errors to webview. see example in screenshot below 
-- 
query text to reproduce 
```sql
config {
type: 'table',
assertions: {
uniqueKey: ["uniqueId"]
}
}
pre_operations {
SET @@query_label = "key:value";
declare SOME_DATE DATE DEFAULT CURRENT_DATE;
}
post_operations {
SELECT
URRENT_TIMESTAMP() AS SOME_TIMESTAMP
}
SELECT
1                AS UNIQUEID
, "myData"       AS SOMECOLUMN
, URRENT_DATE() AS TODAYS_DATE
```
> feat: propagate pre and post operation errors to webview

- .gitignore
- package.json
- src/utils.ts
> feat: typescript code refactor 

- src/utils.ts
Fixes: https://github.com/ashish10alex/vscode-dataform-tools/issues/89
Although the underlying data structure in operations key in `dataform compile --json`  in `queries` which is a list. So this would indicate that there could be multiple of these. However, I am yet to see an example of such a case. which is why we had added a semicolon as a terminator. For now we are moving to empty string as delimiter.  Such that the final output on webview is consistent with what is shown in GCP Dataform UI.
> fix: #89 semicolon added to end of operations

- package.json
- src/bigqueryClient.ts
Solves: https://github.com/ashish10alex/vscode-dataform-tools/issues/116
> fix: unable to use bigquery client when global default project does have BigQuery enabled 

- package.json
- src/extension.ts
- src/formatCurrentFile.ts
- src/views/register-preview-compiled-panel.ts
Solves: https://github.com/ashish10alex/vscode-dataform-tools/issues/117
> feat: support for native `format Document` 

- media/js/showQueryResults.js
- src/bigqueryRunQuery.ts
Solves: https://github.com/ashish10alex/vscode-dataform-tools/issues/125
we will be using `x` as the separator for struct column as using `.`  is resulting in no data being shown when using Tabulator
Test query
```sql
SELECT
11 as qty,
STRUCT(
'HELLO WORLD 1' as field_1,
'HELLO WORLD 2' as field_2
) as hello,
"my_data" as foo,
id,
ARRAY<STRING>['string1', 'string2', 'string3'] AS StringArray,
ARRAY(
SELECT AS STRUCT * FROM UNNEST([]) AS EmptyArrayCol
) AS EmptyArray,
ARRAY(
SELECT AS STRUCT * FROM UNNEST([]) AS AnotherEmptyArrayCol
) AS AnotherEmptyArrayCol,
ARRAY(
SELECT AS STRUCT * FROM UNNEST(GENERATE_ARRAY(1, 3)) AS PopulatedArrayCol
) AS PopulatedArray,
ARRAY(
SELECT AS STRUCT * FROM UNNEST(GENERATE_ARRAY(1, 5)) AS PopulatedArrayMoreItems
) AS PopulatedArrayMoreItems,
ARRAY(
SELECT …
```
> fix: data preview cannot render struct types

- media/js/showCompiledQuery.js
- src/bigqueryDryRun.ts
- src/types.ts
- src/utils.ts
- src/views/register-preview-compiled-panel.ts
Solve: https://github.com/ashish10alex/vscode-dataform-tools/issues/128
**Tests**
> feat: make multiple views/tables query visible from a single .js file

- src/utils.ts
- src/views/register-preview-compiled-panel.ts
remove redundant active model metadata parsing. From the tests it does not result in perceivable latency improvement perhaps due to how fast the operation is.
> feat: remove redundant active model metadata parsing

- media/js/showQueryResults.js
- src/bigqueryRunQuery.ts
- src/views/register-query-results-panel.ts
Fixes: https://github.com/ashish10alex/vscode-dataform-tools/issues/131
Results of running multiple assertions will show as follows. Clicking "View Results" shows you the table with the results from the assertions if it has failed. If the assertion has passed, there will be assertion passed banner. Also, you can see the query the assertion was ran with in both failure and passing cases.
> fix: multiple assertions when ran does not show the correctly show failed assertions

- src/bigqueryRunQuery.ts
Test query that needs to pass 
```sql
config {
type: 'operations',
name: "test2"
}
SELECT
11 as qty,
STRUCT(
'HELLO WORLD 1' as field_1,
'HELLO WORLD 2' as field_2
) as t_struct,
"my_data" as t_string,
name,
laps,
times,
ARRAY<STRING>['string1', 'string2', 'string3'] AS StringArray,
ARRAY(
SELECT AS STRUCT * FROM UNNEST([]) AS EmptyArrayCol
) AS EmptyArray,
ARRAY(
SELECT AS STRUCT * FROM UNNEST(GENERATE_ARRAY(1, 3)) AS PopulatedArrayCol
) AS PopulatedArray,
ARRAY(
SELECT AS STRUCT * FROM UNNEST(GENERATE_ARRAY(1, 5)) AS PopulatedArrayMoreItems
) AS PopulatedArrayMoreItems,
ARRAY(
SELECT AS STRUCT * FROM UNNEST(GENERATE_DATE_ARRAY(CURRENT_DATE(), CURRENT_DATE() + 6, INTERVAL 1 day)) AS dateArray
) AS dateArray,
FROM 
UNNEST(
[
STRUCT(1 as id, "Murphy" AS name, [23.9, 26.0, 27.0, 26.0] AS …
```
> fix: unnested struct columns not showing in results preview

- .vscode-test.mjs
- package-lock.json
- package.json
- src/test/suite/extension.test.ts
- src/test/suite/helper.ts
This PR:
1. Fixes issue with vscode tests not running due to
- the path of the compiled test js files being incorrect 
- the test sqlx file not being picked up correctly as their parent dir was not correctly inferred 
3. Updates `@vscode/test-electron` to `^2.5.2`
NOTE: The tests used to work before as is. But in one of the releases I might have changed the path of how all ts files are compiled resulting in the regression.
> fix: extension tests not running due to path issues

- src/test/suite/extension.test.ts
- src/utils.ts
Fixes: https://github.com/ashish10alex/vscode-dataform-tools/issues/160
Testing:
**Error:**
**Fixed**
> fix: incorrect termination of pre-orations when comment is present

- package.json
- src/constants.ts
- src/extension.ts
- src/types.ts
- src/utils.ts
- src/views/register-preview-compiled-panel.ts
TL;DR: Path Detection Overhaul
This PR fixes executable path detection for tools installed via managers (`asdf`, `mise`, etc.) by replacing the simple `which` command with a more robust system.
**Please review the following key areas:**
1.  **Detection Logic (`src/utils.ts`):**
A new 3-tier detection priority has been implemented:
1.  User-configured path (new setting)
2.  System `PATH` search
3.  Common tool manager locations (Homebrew, asdf, etc.)
Is this search order robust? Are we missing any common installation paths?
2.  **Caching Strategy (`src/utils.ts`):**
An in-memory, 5-minute cache was added to prevent repeated filesystem lookups.
Is a 5-minute cache duration a reasonable default?
3.  **Configuration (`package.json`):**
Added optional `dataformExecutablePath` and …
> refactored CLI binary location to be more resiliant

- package-lock.json
- package.json
- src/constants.ts
- src/createNewDataformProject.ts
- src/extension.ts
- src/initDataformProject.ts
- src/utils.ts
Allows the user to create a new Dataform repository via `Dataform: Initialize a new Dataform project` command. On the command invocation user will be prompted to 
1. Select the root directory where Dataform project will be created. If it is already a Dataform project then creation will be aborted
2. Select default location from the list of pre-populated locations. E.g. europe-west2 etc. 
3. Select GCP project Id from list of GCP project Ids available to the user when they have authenticated via gcloud . The list of project ids are populated using [@google-cloud/resource-manager](https://www.npmjs.com/package/@google-cloud/resource-manager) npm package adding to the chunkiness of the vscode extension. 
A new workspace will be opened where the new Dataform project can be explored. 
Tests
> feat: command to create a new Dataform project

- src/utils.ts
Addresses : https://github.com/ashish10alex/vscode-dataform-tools/issues/192
Extension will show the expected compilation error than the error that the file extension is not one of the supported ones.
> fix: file extension not correctly inferred when there are multiple periods in the filename
